### PR TITLE
Provision local IP and assign virtual hostname

### PR DESCRIPTION
**Pull request by Johnstonian**
This change will prevent possible port collisions with other projects that use port 8080. The developer can simply goto http://vagrantpress.dev and vagrant will autocorrect the port if needed. Based on this suggestion in the issues list: https://github.com/chad-thompson/vagrantpress/issues/83

The client's host file will be updated as well with the vagrant-hostupdater plugin.

This does create an extra step and an additional prerequisite. The prerequisite being Vagrant Hostupdater and the extra step being 'vagrant plugin install vagrant-hostsupdater'.

The approach appears to be cleaner and will prevent potential issues with delcaring a port as part of the wordpress blog url when creating the wordpress instance. Now, regardless of which port is selected by vagrant, the wordpress instance will be accessible via http://vagrantpress.dev. When the vagrant instance is destroyed, the plugin will remove the specific IPs in the client's host file provisioned to the project.

[Review on Reviewable](https://reviewable.io/reviews/chad-thompson/vagrantpress/91)

### CODE REVIEW

**Comment by battlemidget** [comment]
:+1:  lgtm

**Comment by najamelan** [comment]
I'm trying to set up a wordpress site in vagrant to develop. I would love to be able to connect to it without having to specify a port number (cause anyways even with a port number I don't get it working right now).

In the readme of your project it seems that you tell users to just point their browser at vagrantpress.dev. I suppose that means their browser will try to connect to port 80 on the host. I don't understand how you open this port... Could you give me some tips, thanks.

**Comment by battlemidget** [comment]
@najamelan When you deploy the vagrant instance it'll have started a web server along with wordpress. That webserver listens on port 80 so vagrantpress.dev is mapped to that.

**Comment by Johnstonian** [comment]
@najamelan, 
@battlemidget  is correct. To expand on the topic a bit:

The Vagrantfile uses a [Private Network](http://docs.vagrantup.com/v2/networking/private_network.html) configuration for the VM. In this instance; a static IP of 192.168.50.4.

```config.vm.network :private_network, :ip => "192.168.50.4"```

This static IP is also added to your machine's host file. The process will add an entry into your host file like this: 

```shell
192.168.50.4  vagrantpress.dev  # VAGRANT: 4eaad839c43c086da5bef3eacb642c2a (default)...
192.168.50.4  www.vagrantpress.dev  # VAGRANT: 4eaad839c43c086da5bef3eacb642c2a (default)...
```
So you can technically get to the project by pointing your browser to http://192.168.50.4. The browser would resolve the IP to vagrantpress.dev.

When you destroy vagrant box, the project will remove the entries from your local host file.

If the IP in the Vagrantfile conflicts with an IP already on your network, you could simply change the IP to whatever you desire.

I hope that helps explain the process a bit more.

**Comment by najamelan** [comment]
Thanks for the explanation. I missed the fact that hostupdater changes the hosts file for the host and not of the guest. I got it working only after changing my private ip adress. For some reason I couldn't even ping my guest when it was in the 192.168.33 range.

**Pull request merged**
